# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/sdk:6.0.4 AS build
WORKDIR /source

# Copy csproj and restore as distinct layers
COPY *.csproj ./

# Copy everything else and build
COPY * ./
RUN dotnet publish -c Release -o app --no-restore

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0.4
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "Prac-API.dll"]